name: Everett Trujillo
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2114695
title: Everett Trujillo Blog
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1E3176'
    - '#060E18'
    - '#4265E6'
    - '#B4FAFF'
    - '#4C6349'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
