title: Everett Trujillo Blog
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5896057
  brandStrength: 0.453405
  lightness: 0.3082437
  brandColors:
    - '#1E3176'
    - '#060E18'
    - '#4265E6'
    - '#B4FAFF'
    - '#4C6349'
  rhythmicContrast: 0.3960573
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Everett Trujillo
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.6577061
layout_spectrum: 0.9408602
