title: Everett Trujillo Blog
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3620072
  lightness: 0.5860215
  brandStrength: 0.5788531
  brandColors:
    - '#1E3176'
    - '#060E18'
    - '#4265E6'
    - '#B4FAFF'
    - '#4C6349'
  rhythmicContrast: 0.6827957
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Everett Trujillo
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.2114695
layout_spectrum: 0.969534
